version: "3.9"

services:
  {{cvmfs_service}}
  
  jupyterhub:
    depends_on:
      - http_proxy
    build: .
    restart: unless-stopped
    command:
      - /usr/bin/python3
      - /usr/local/bin/jupyterhub
      - --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/dodasts/jupyterhub/cookies:/srv/jupyterhub/cookies
      - /usr/local/share/dodasts/jupyterhub/db:/srv/jupyterhub/db
    environment:
      - OAUTH_ENDPOINT={{iam_url}}
      - OAUTH_CALLBACK_URL=https://{{server_ip}}:{{jupyter_port}}/hub/oauth_callback
      - OAUTH_GROUPS={{iam_groups}}
      - {{jupyter_gpu}}
      - ADMIN_OAUTH_GROUPS={{iam_admin_groups}}

  http_proxy:
    image: jupyterhub/configurable-http-proxy
    restart: unless-stopped
    command:
      - configurable-http-proxy
      - --ip=0.0.0.0
      - --port={{jupyter_port}}
      - --api-ip=0.0.0.0
      - --api-port=8001
      - --default-target=http://jupyterhub:8088
      - --error-target=http://jupyterhub:8088/hub/error
      - --ssl-key=/usr/local/share/dodasts/certs/jupyter/hostcert.key
      - --ssl-cert=/usr/local/share/dodasts/certs/jupyter/hostcert.pem
    volumes:
      - /usr/local/share/dodasts/certs/jupyter:/usr/local/share/dodasts/certs/jupyter
    environment:
      - CONFIGPROXY_AUTH_TOKEN={{jupyter_proxy_token}}
    ports:
      - {{jupyter_port}}:{{jupyter_port}}
      - 8001:8001

networks:
  default:
    name: jupyterhub
